require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'config/deploy.rb'
    - 'vendor/**/*'

Lint/UselessAssignment:
  Exclude:
    - 'spec/models/index_event_spec.rb'

Style/FileName:
  Exclude:
    - '**/Gemfile'
    - '**/*.rake'
    - 'Capfile'