require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'config/deploy.rb'
    - 'vendor/**/*'

Lint/UselessAssignment:
  Exclude:
    - 'spec/models/index_event_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'spec/**/*'
    - 'config/initializers/*'
    - 'lib/tasks/lae.rake'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
    - 'app/indexers/plum_jsonld_converter.rb'
    - 'spec/support/stub_plum_catalog.rb'
    - 'app/services/solr_document_metadata.rb'
Metrics/ClassLength:
  Exclude:
    - 'app/indexers/plum_jsonld_converter.rb'
Metrics/AbcSize:
  Exclude:
    - 'app/indexers/plum_jsonld_converter.rb'
Metrics/LineLength:
  Exclude:
    - 'spec/indexers/plum_jsonld_converter_spec.rb'
RSpec/SubjectStub:
  Exclude:
    - 'spec/indexers/plum_jsonld_converter_spec.rb'

Rails/Output:
  Exclude:
    - 'app/models/index_event.rb'

Rails/TimeZone:
  Exclude:
    - 'lib/tasks/lae.rake'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/SubjectStub:
  Exclude:
    - 'spec/workers/plum_event_handler_spec.rb'
    - 'spec/indexers/plum_jsonld_converter_spec.rb'

Style/FileName:
  Exclude:
    - '**/Gemfile'
    - '**/*.rake'
    - 'Capfile'

Style/BracesAroundHashParameters:
  Exclude:
    - spec/services/solr_document_metadata_spec.rb
Metrics/ModuleLength:
  Exclude:
    - app/helpers/application_helper.rb
Rails/OutputSafety:
  Exclude:
    - app/helpers/application_helper.rb
RSpec/MessageSpies:
  Exclude:
    - spec/indexers/plum_jsonld_converter_spec.rb
