language: ruby
sudo: false
rvm:
  - 2.3.1

before_script:
  - cp config/database.yml.travis config/database.yml
  - cp config/blacklight.yml.tmpl config/blacklight.yml
  - cp config/secrets.yml.tmpl config/secrets.yml
  - mysql -e 'create database lae_blacklight_test;'
  - jdk_switcher use oraclejdk8

before_install:
  - gem update bundler

script: bundle exec rake ci

branches:
  only:
    - master
notifications:
  email:
    recipients:
      - "jstroop@princeton.edu"
      - "kr2@princeton.edu"
    on_success: "change"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
