version: "3.8"
services:
  web:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY_BASE=1111111
      - DB_HOST=postgres-db
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=rails
      - SOLR_URL=http://solr:8983/solr/core
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 5s
      retries: 30

  solr:
    image: "solr:8.4"
    volumes:
      - "./solr/conf:/core/conf"
    command: "solr-precreate core /core"
