version: 2
jobs:
  build:
    # Primary command image where all commands run
    docker:
      - image: circleci/ruby:2.4.5-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
      # Service container image available at 'host: localhost'
      - image: postgres:10
        environment:
          POSTGRES_DB: lae_blacklight_test
          POSTGRES_USER: root
          POSTGRES_HOST_AUTH_METHOD: trust
    working_directory: ~/lae-blacklight
    steps: &test_steps
      - checkout
      - run:
          name: Install node@8.17.0 (need right version for `yarn`)
          command: |
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install v8.17.0' >> $BASH_ENV
            echo 'nvm alias default v8.17.0' >> $BASH_ENV
      - run:
          name: Check current version of node
          command: node -v
      #set timezone to est
      - run:
          name: Set Timezone to EST
          command: echo 'America/New_York' = /etc/timezone

      # Restore bundle cache
      - restore_cache:
          keys:
          - lae-blacklight-{{ checksum "Gemfile.lock" }}
          - lae-blacklight-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt update

      - save_cache:
          key: lae-blacklight-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      - run:
          name: Start Solr test instance
          command: bundle exec rake server:test
          background: true

      - run: bin/jetty_wait

      - run:
          name: npm install
          command: npm install

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bundle exec rake db:setup

      - run:
          name: Run rubocop
          command: bundle exec rake rubocop

      - run:
          name: Index lae fixtures
          command: bundle exec rake lae:index_fixtures

      - run:
          name: Run Rspec
          command: bundle exec rspec spec
  test_2_6:
    # Primary command image where all commands run
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
      # Service container image available at 'host: localhost'
      - image: postgres:10
        environment:
          POSTGRES_DB: lae_blacklight_test
          POSTGRES_USER: root
          POSTGRES_HOST_AUTH_METHOD: trust
    working_directory: ~/lae-blacklight
    steps: *test_steps
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - test_2_6
