version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    # Primary command image where all commands run
    docker:
      - image: cimg/ruby:3.1.0-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test
          SOLR_URL: http://solr:SolrRocks@localhost:8888/solr/lae-core-test
      # Service container image available at 'host: localhost'
      - image: postgres:15
        environment:
          POSTGRES_DB: lae_blacklight_test
          POSTGRES_USER: root
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: solr:7.7-alpine
        command: bin/solr -cloud -noprompt -f -p 8888
    working_directory: ~/lae-blacklight
    steps: &test_steps
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.15'
      - run: node --version
      #set timezone to est
      - run:
          name: Set Timezone to EST
          command: echo 'America/New_York' = /etc/timezone

      # Restore bundle cache
      - restore_cache:
          keys:
          - lae-blacklight-{{ checksum "Gemfile.lock" }}
          - lae-blacklight-
      # Install Bundler
      - run: gem install bundler -v '~> 2.0'
      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - run: sudo apt update
      - save_cache:
          key: lae-blacklight-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: Yarn Install
          command: |
            source ~/.nvm/nvm.sh
            yarn install

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Load config into solr
          command: |
            cd solr/conf
            zip -1 -r solr_config.zip ./*
            curl -H "Content-type:application/octet-stream" --data-binary @solr_config.zip "http://localhost:8888/solr/admin/configs?action=UPLOAD&name=lae"
            curl -H 'Content-type: application/json' http://localhost:8888/api/collections/ -d '{create: {name: lae-core-test, config: lae, numShards: 1}}'
      - run:
          name: Database setup
          command: bundle exec rake db:setup

      - run:
          name: Run rubocop
          command: bundle exec rubocop
      - run:
          name: Index lae fixtures
          command: bundle exec rake lae:index_fixtures

      - run:
          name: Run Rspec
          command: bundle exec rspec spec
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
