development: &default
  adapter: postgresql
  database: lae_development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 30)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 20)) %>
  timeout: 5000

test:
  <<: *default
  database: lae_test

production: &deploy
  <<: *default
  adapter: postgresql
  database: <%= ENV["LAE_DB"] %>
  host: <%= ENV["LAE_DB_HOST"] %>
  username: <%= ENV["LAE_DB_USERNAME"] %>
  password: <%= ENV["LAE_DB_PASSWORD"] %>

staging: *deploy
