# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9409c53cd6b973db2f9832a416fbb63b228ebbf662562263bd40de871411987d4d69bf43447bbc7cabc73a9b361136fc463560f4c30199786516c38f6e86a908

test:
  secret_key_base: 458d53ce4f456b783b9dcddbada6cc85f44873341871babc3392c4cec367688dba7941e0443ed4f949c0033a64b26243652c3cc22d3bd4df6396a1eeb4d0cb79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
