default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default
  secret_key_base: "f9d5529fa6ff1cb0066b3e89c564bb7b02b4ed2f77a040fc39de5bf9ac2c3d7145d034848ed3271ad2844428d"

test:
  <<: *default
  secret_key_base: "asdf9hasdf89hasd9f8has9dfnasidfbalfblsfd"

staging:
  <<: *default

production:
  <<: *default
